### ISSUE TITLE
Portierung aller Plugins auf v2

### ISSUE THREAD

**Issue by Brawl345** [Brawl345/Brawlbot-v2#1]
**UPDATE:** Ich hab mal die Liste aufgeräumt.
Ein Großteil der Plugins der Version 1 des Brawlbots werden auf Version 2 portiert. Das meiste ist copy&paste, nur ein bisschen muss angepasst werden. Nicht sonderlich schwierig, aber sehr nervig und zeitaufwändig. Hier eine Liste aller noch fehlenden Plugins:

- [ ] Isup
- [x] Youtube_dl

**Comment by Akamaru** [comment]
[media_download.txt](https://github.com/Brawl345/Brawlbot-v2/files/317210/media_download.txt)

media_download.lua is nich dabei ._.

**Comment by Brawl345** [comment]
Jetzt schon :P

**Comment by Brawl345** [comment]
Hier noch eine Liste aller Plugins, die nicht portiert werden (und der Grund, wieso)

- **chat_name**: Keine Möglichkeit zum Ändern des Gruppenfotos- und -namen per API, allerdings eh überflüssig geworden, da Gruppenadmins möglich sind
- **service_reset_chatname**: Gleicher Grund

Dieser Post wird aktualisiert, falls etwas dazukommt.
